[project]
name = "projetcrag"
version = "0.1.0"
description = "Assistant RAG local pour interroger des documents PDF"
readme = "README.md"
authors = [
    { name = "fidelemiakanda", email = "sefimiakanda@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pypdf>=6.19.0",
    "sentence-transformers>=6.1.0",
    "streamlit>=1.54.0",
]

[project.scripts]
projetcrag = "projetcrag:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
