[project]
name = "projetcrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fidelemiakanda", email = "sefimiakanda@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.3",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.12",
    "pypdf>=6.19.0",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.1.0",
    "tiktoken>=0.14.0",
]

[project.scripts]
projetcrag = "projetcrag:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
